name: Fly Deploy

on:
  push:
    branches: [ master ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  environment: "${{ github.ref == 'refs/heads/master' && 'Production' || 'Dev' }}"

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Setup HoneyComb
        uses: kvrhdn/gha-buildevents@v1
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: ${{ env.environment }}-Discord
          job-status: ${{ job.status }}

      - run: echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
      - run: buildevents step $TRACE_ID 'actions/checkout@v2' $STEP_START 'Checkout Code'

      - run: echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - name: Create Config.py
        run: echo "$BOT_CONFIG" > config.py
        shell: bash
        env:
          BOT_CONFIG: ${{secrets.BOT_CONFIG}}
      - run: buildevents step $TRACE_ID 'create_config' $STEP_START 'Create Config.py'

      - run: echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - name: Deploy to Fly
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy -a ${{ secrets.FLY_APP_NAME }}"
      - run: buildevents step $TRACE_ID 'superfly/flyctl-actions@1.3:deploy' $STEP_START 'Deploy to Fly'
