name: Fly Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://vikesec.ca/discord
    concurrency:
      group: "prod"
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Config.py
        run: echo "$BOT_CONFIG" > config.py
        shell: bash
        env:
          BOT_CONFIG: ${{secrets.BOT_CONFIG}}

      - name: Deploy to Fly
        uses: superfly/flyctl-actions@1.3
        with:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          args: "deploy -a ${{ secrets.FLY_APP_NAME }}"

      - name: Upload OTEL traces
        uses: MNThomson/otel-action@master
        with:
          endpoint: "https://api.honeycomb.io/"
          headers: "x-honeycomb-team=${{ secrets.HC_API_TOKEN }}"
          service_name: "VikeBot"
