name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setenv:
    name: Black Lint
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.setenv.outputs.env }}
    steps:
      - id: setenv
        run: echo "::set-output name=env::${{ github.ref == 'refs/heads/master' && 'prod' || 'stage' }"

  black:
    name: Black Lint
    runs-on: ubuntu-latest
    needs: setenv
    environment:
      name: ${{ needs.setenv.outputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Black Lint
        uses: psf/black@stable
        with:
          options: "--check"

  isort:
    name: Isort Lint
    runs-on: ubuntu-latest
    needs: setenv
    environment:
      name: ${{ needs.setenv.outputs.env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Create Config.py
        run: touch config.py
        shell: bash

      - name: Isort Lint
        uses: isort/isort-action@v0.1.0
        with:
          sortPaths: "**/*.py"
          configuration: "--check --color"
