name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  black:
    name: Black Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Config.py
        run: echo '${{ secrets.BOT_CONFIG }}' > config.py

      - uses: psf/black@stable
        with:
          options: "--check"

      - uses: psf/black@stable
        if: failure()
        with:
          options: "--check --diff"

  isort:
    name: Isort Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Config.py
        run: echo '${{ secrets.BOT_CONFIG }}' > config.py

      - name: Install Isort
        run: |
          python -m pip install isort

      - name: Run Isort
        uses: isort/isort-action@master
