name: Staging

on:
  pull_request:
    branches: [master]

env:
  environment: "${{ github.ref == 'refs/heads/master' && 'Production' || 'Dev' }}"

jobs:
  stagebot:
    name: Run StageBot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        run: echo "$BOT_CONFIG" > config.py
        shell: bash
        env:
          BOT_CONFIG: ${{secrets.BOT_CONFIG}}

      - name: Change stage slash commands to have 'z' infront
        run: >
          find . -type f -name "*.py" -not -path '*/\.*' -exec
          sed -i 's/SlashCommandGroup("/SlashCommandGroup("z/g' {} +
        shell: bash

      - name: Build Docker image
        run: docker build -t vikaxe/haxebot:${{ github.sha }} .

      - name: Run StageBot
        run: docker run -e "BOT_TOKEN=$STAGE_TOKEN" -e "BOT_ENV=staging" vikaxe/haxebot 1>/dev/null 2>&1
        shell: bash
        continue-on-error: true
        env:
          STAGE_TOKEN: ${{secrets.STAGE_TOKEN}}
