name: Staging

on:
  pull_request:
    branches: [ master ]

jobs:
  stagebot:
    name: Run StageBot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Config.py
        run: echo "$BOT_CONFIG" > config.py
        shell: bash
        env:
          BOT_CONFIG: ${{secrets.BOT_CONFIG}}

      - name: Build docker image
        run: docker build -t vikaxe/haxebot .
        shell: bash

      - name: Run StageBot
        run: docker run -e "BOT_TOKEN=$STAGE_TOKEN" -e "BOT_ENV=staging" vikaxe/haxebot
        shell: bash
        continue-on-error: true
        env:
          STAGE_TOKEN: ${{secrets.STAGE_TOKEN}}
